services:
  app-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    profiles: ["dev"]
    container_name: hono-dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3000
    networks:
      - app-network
    restart: unless-stopped

  app-prod:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    env_file:
      - .env
    profiles: ["prod"]
    container_name: hono-prod
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  app-network:
    driver: bridge
