allowBuilds:
  esbuild: true
minimumReleaseAgeExclude:
  - effect@3.21.4
  - '@biomejs/biome@2.5.4'
  - '@biomejs/cli-darwin-arm64@2.5.4'
  - '@biomejs/cli-darwin-x64@2.5.4'
  - '@biomejs/cli-linux-arm64-musl@2.5.4'
  - '@biomejs/cli-linux-arm64@2.5.4'
  - '@biomejs/cli-linux-x64-musl@2.5.4'
  - '@biomejs/cli-linux-x64@2.5.4'
  - '@biomejs/cli-win32-arm64@2.5.4'
  - '@biomejs/cli-win32-x64@2.5.4'
  - '@hono/standard-validator@0.3.0'
  - '@hono/zod-validator@0.9.0'
minimumReleaseAgeStrict: true
onlyBuiltDependencies:
  - better-sqlite3
  - esbuild
